SELECT * FROM SPAREPART;

DROP TABLE SPAREPART;

CREATE TABLE SPAREPART(
SP_ID        NUMBER PRIMARY KEY,
SP_NAME      VARCHAR(100),
SP_RATE      NUMBER,
SP_UNIT      VARCHAR(20));


SELECT * FROM SPAREPART;

INSERT INTO SPAREPART VALUES(4001,'TWO WHEELER TUBE',250,'NOS');

INSERT INTO SPAREPART VALUES(4002,'TWO WHEELER ENGINE OIL',400,'LTRS');

INSERT INTO SPAREPART VALUES(4003,'FOUR WHEELER ENGINE OIL',5000,'LTRS');
INSERT INTO SPAREPART VALUES(4004,'TWO WHEELER CARBORATOR',680,'NOS');
INSERT INTO SPAREPART VALUES(4005,'TWO WHEELER CLUTCH WIRE',129,'MTRS');
INSERT INTO SPAREPART VALUES(4006,'TWO WHEELER TAIL LIGHT',100,'NOS');
INSERT INTO SPAREPART VALUES(4007,'TWO WHEELER INDICATORS',150,'NOS');
INSERT INTO SPAREPART VALUES(4008,'FOUR WHEELER GASKIT',1340,'NOS');
INSERT INTO SPAREPART VALUES(4009,'WHITE COLOR',340,'LTRS');
INSERT INTO SPAREPART VALUES(4010,'BLACK COLOR',240,'LTRS');
INSERT INTO SPAREPART VALUES(4011,'TWO WHEELER SIDE MIRROR',250,'NOS');
INSERT INTO SPAREPART VALUES(4012,'FOUR WHEELER SIDE MIRROR',450,'NOS');
INSERT INTO SPAREPART VALUES(4013,'TWO WHEELE SHOCKUP',1320,'PAIR');
INSERT INTO SPAREPART VALUES(4014,'FOUR WHEELER BUMPER',6000,'NOS');
INSERT INTO SPAREPART VALUES(4015,'FOUR WHEELER FRONT GLASS',7000,'PCS');
